#index:
#    path: /
#    controller: App\Controller\DefaultController::index

controllers:
    resource: ../src/Blog/Controller/
    type: annotation

api_login_check:
    path: /api/login_check
api:
    resource: '.'
    type: 'api_platform'
    prefix: '/api' # Optional
swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui
